# Generated by Django 5.1.2 on 2025-10-30 14:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='category/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Үйірме атауы')),
                ('description', models.TextField(verbose_name='Сипаттама')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs/', verbose_name='Сурет')),
                ('icon', models.CharField(blank=True, help_text='FontAwesome иконка классы, мысалы: fas fa-code', max_length=100, verbose_name='Иконка классы')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Үйірме',
                'verbose_name_plural': 'Үйірмелер',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырыбы')),
                ('content', models.TextField(verbose_name='Мазмұны')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Сурет')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Жарияланған күні')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Жаңалық',
                'verbose_name_plural': 'Жаңалықтар',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='slider/')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Аты-жөні')),
                ('position', models.CharField(choices=[('teacher', 'Мұғалім'), ('administrator', 'Әкімшілік'), ('director', 'Директор'), ('other', 'Басқа')], max_length=50, verbose_name='Лауазымы')),
                ('image', models.ImageField(upload_to='staff/', verbose_name='Сурет')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('experience', models.IntegerField(default=0, verbose_name='Тәжірибесі (жыл)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
                ('order', models.IntegerField(default=0, verbose_name='Реттік номер')),
            ],
            options={
                'verbose_name': 'Қызметкер',
                'verbose_name_plural': 'Қызметкерлер',
                'ordering': ['order', 'name'],
            },
        ),
    ]
