# Generated by Django 5.1.2 on 2026-03-12 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('subject', models.CharField(blank=True, max_length=200, verbose_name='Тақырыбы')),
                ('message', models.TextField(verbose_name='Хабарлама')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жіберілген уақыты')),
                ('is_read', models.BooleanField(default=False, verbose_name='Оқылды')),
            ],
            options={
                'verbose_name': 'Хабарлама',
                'verbose_name_plural': 'Хабарламалар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Атауы')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Құжат санаты',
                'verbose_name_plural': 'Құжат санаттары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GalleryAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Атауы')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='gallery/covers/', verbose_name='Мұқаба')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
            ],
            options={
                'verbose_name': 'Фотоальбом',
                'verbose_name_plural': 'Фотоальбомдар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Атауы')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Жаңалық санаты',
                'verbose_name_plural': 'Жаңалық санаттары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Тақырыбы')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Мазмұны')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Сурет')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
            ],
            options={
                'verbose_name': 'Бет',
                'verbose_name_plural': 'Беттер',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тақырыбы')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Қосымша мәтін')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='Сурет')),
                ('link', models.URLField(blank=True, verbose_name='Сілтеме')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
                ('is_active', models.BooleanField(default=True, verbose_name='Белсенді')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайдер',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Аты-жөні')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='Фото')),
                ('subject', models.CharField(max_length=150, verbose_name='Пәні')),
                ('experience', models.PositiveIntegerField(default=0, verbose_name='Тәжірибесі (жыл)')),
                ('description', models.TextField(blank=True, verbose_name='Сипаттама')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
            ],
            options={
                'verbose_name': 'Мұғалім',
                'verbose_name_plural': 'Мұғалімдер',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Атауы')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Жүктелген уақыты')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='app.documentcategory', verbose_name='Санаты')),
            ],
            options={
                'verbose_name': 'Құжат',
                'verbose_name_plural': 'Құжаттар',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/', verbose_name='Сурет')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Тақырыбы')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Жүктелген уақыты')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.galleryalbum', verbose_name='Альбом')),
            ],
            options={
                'verbose_name': 'Галерея суреті',
                'verbose_name_plural': 'Галерея суреттері',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Тақырыбы')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='URL')),
                ('text', models.TextField(verbose_name='Мәтіні')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Сурет')),
                ('is_published', models.BooleanField(default=True, verbose_name='Жарияланған')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылған уақыты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылған уақыты')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='app.newscategory', verbose_name='Санаты')),
            ],
            options={
                'verbose_name': 'Жаңалық',
                'verbose_name_plural': 'Жаңалықтар',
                'ordering': ['-created_at'],
            },
        ),
    ]
