# Generated by Django 5.1.2 on 2026-03-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Атауы')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Мазмұны')),
                ('image', models.ImageField(blank=True, null=True, upload_to='clubs/', verbose_name='Сурет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Реттілік')),
            ],
            options={
                'verbose_name': 'Үйірме',
                'verbose_name_plural': 'Үйірмелер',
                'ordering': ['order', 'name'],
            },
        ),
    ]
